/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.bookrecommendation.gui;
import com.bookrecommendation.model.User;

/**
 *
 * @author lepto
 */
public class MainPage extends javax.swing.JFrame {
    
    private User currentUser;

    /** Creates new form MainPage */
    /** Creates new form MainPage */
    public MainPage() {
        this(null);
    }

    public MainPage(User currentUser) {
        this.currentUser = currentUser;
        initComponents();
        initCustomLogic();
    }
    
    
    private void initCustomLogic() {
        // Κάνε τα κουμπιά “αόρατα” πάνω στην εικόνα
        makeButtonInvisible(jButton1); // Books
        makeButtonInvisible(jButton2); // Orders
        makeButtonInvisible(jButton3); // Users
        makeButtonInvisible(jButton4); // My orders
        makeButtonInvisible(jButton5); // Log file
        makeButtonInvisible(jButton6); // Log out
       
        // Hand cursor
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // ΛΟΓΙΚΗ ΚΟΥΜΠΙΩΝ
        // 1. Books
        jButton1.addActionListener(e -> openBooks());

        // 2. Orders
        jButton2.addActionListener(e -> openOrders());

        // 3. Users
        jButton3.addActionListener(e -> openUsers());

        // 4. My orders
        jButton4.addActionListener(e -> openMyOrders());

        // 5. Log file
        jButton5.addActionListener(e -> openLogFile());

        // 6. Log out
        jButton6.addActionListener(e -> logOut());
    }

    private void makeButtonInvisible(javax.swing.JButton b) {
        b.setText("");                 // το κείμενο υπάρχει ήδη στην εικόνα
        b.setBorderPainted(false);
        b.setContentAreaFilled(false);
        b.setFocusPainted(false);
        b.setOpaque(false);
    }

    // ==== ΕΔΩ ΒΑΖΕΙΣ ΤΙ ΚΑΝΕΙ ΚΑΘΕ ΚΟΥΜΠΙ ====

    private void openBooks() {
        BookPage bookPage = new BookPage(this);
        bookPage.setLocationRelativeTo(this);
        bookPage.setVisible(true);
        this.setVisible(false);
    }

    private void openOrders() {
        OrdersPage ordersPage = new OrdersPage(this);
        ordersPage.setLocationRelativeTo(this);
        ordersPage.setVisible(true);
        this.setVisible(false);
    }

    private void openUsers() {
        UsersPage usersPage = new UsersPage(this);
        usersPage.setLocationRelativeTo(this);
        usersPage.setVisible(true);
        this.setVisible(false);
    }


    private void openMyOrders() {
        if (currentUser == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Δεν υπάρχει συνδεδεμένος χρήστης.");
            return;
        }

        MyOrdersPage myOrdersPage = new MyOrdersPage(this, currentUser.getUsername());
        myOrdersPage.setLocationRelativeTo(this);
        myOrdersPage.setVisible(true);
        this.setVisible(false);
    }


    private void openLogFile() {


       LogFile logFile = new LogFile(this);
    logFile.setLocationRelativeTo(this);
    logFile.setVisible(true);
    this.setVisible(false);
    }

    private void logOut() {
        // Επιστροφή στην αρχική οθόνη (MainJFrame)
        MainJFrame start = new MainJFrame();
        start.setLocationRelativeTo(this);
        start.setVisible(true);

        // κλείσε το MainPage
        this.dispose();
    }
   
                    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bookrecommendation/images/main.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 740));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 180, 70));

        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 190, 70));

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 190, 70));

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 230, 70));

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 170, 70));

        jButton6.setText("jButton6");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 120, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
